

--아이디 및 권한 생성 -- 
create user youthmarket identified by g1234;
grant dba to youthmarket;

--관리자 -- 
drop table admin cascade constraints;

CREATE TABLE ADMIN (
    ADMIN_ID        VARCHAR2(20)  NOT NULL,
    ADMIN_PASSWORD  VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_ADMIN PRIMARY KEY (ADMIN_ID)
);
insert into admin values(
	'youth', '1234'
);


--공지사항
CREATE TABLE ADMIN_NOTICE (
    NOTICE_NO      NUMBER          NOT NULL PRIMARY KEY, 
    NOTICE_TYPE    VARCHAR2(20)    NOT NULL,
    NOTICE_TITLE   VARCHAR2(200)   NOT NULL,
    NOTICE_WRITER  VARCHAR2(15)    NOT NULL,
    NOTICE_IMG     VARCHAR2(500)   NULL,
    NOTICE_HIT     NUMBER          NULL,
    CREATE_DATE    DATE            DEFAULT SYSDATE
);
--게시판 -- 
drop table notice cascade constraints;
drop * from table notice;
CREATE TABLE NOTICE (
    NOTICE_NO      NUMBER          NOT NULL ,
    NOTICE_TYPE    VARCHAR2(10)    NOT NULL,
    NOTICE_TITLE   VARCHAR2(200)   NOT NULL ,
    NOTICE_WRITER  VARCHAR2(15)    NOT NULL ,
    NOTICE_IMG     VARCHAR2(500)   NULL     ,
    NOTICE_HIT     NUMBER          NULL     ,
    CREATE_DATE    DATE         DEFAULT SYSDATE ,
    CONSTRAINT PK_NOTICE PRIMARY KEY (NOTICE_NO)
);

select * from member;
-- 회원 정보 -- 
drop table member cascade constraints;
select * from member;
CREATE TABLE MEMBER (
    USER_NO       NUMBER         NOT NULL,
    USER_ID            VARCHAR2(20)   NOT NULL,
    USER_PASSWORD      VARCHAR2(100)  NOT NULL,
    USER_NAME     VARCHAR2(100),
    PHONE         VARCHAR2(30),
    BIRTH         VARCHAR2(30),
    EMAIL         VARCHAR2(100),
    COUNT         NUMBER         NOT NULL,
    CREATE_DATE   DATE           NOT NULL,
    STATUS        CHAR(1) DEFAULT 'Y',
    heartCount    NUMBER(10),
    BLACKLIST     CHAR(1) DEFAULT 'N',
    account       varchar2(20),
	reportCount   number(10), 
	filename      varchar2(100),
    CONSTRAINT PK_MEMBER PRIMARY KEY (USER_NO)
);


--카테 고리 --

CREATE TABLE CATEGORY (
    CATEGORY_NO    NUMBER        NOT NULL,
    CATEGORY_NAME  VARCHAR2(100) NOT NULL,
    CONSTRAINT PK_CATEGORY PRIMARY KEY (CATEGORY_NO)
);

INSERT INTO CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (1, '인기순');
INSERT INTO CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (1, '인기순');
INSERT INTO CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (10, '디지털기기');
INSERT INTO CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (20, '생활가전');
INSERT INTO CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (30, '유아용품');
INSERT INTO CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (40, '패션');
INSERT INTO CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (50, '도서');
INSERT INTO CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (60, '반려동물용품');
INSERT INTO CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (70, '스포츠');
INSERT INTO CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (80, '뷰티');
INSERT INTO CATEGORY (CATEGORY_NO, CATEGORY_NAME) VALUES (90, '교환권');

-- 판매 게시글 --
drop table sell cascade constraint;
CREATE TABLE SELL (
    SELL_NO      NUMBER        NOT NULL , 
    SELL_TITLE   VARCHAR2(100) NOT NULL ,
    SELL_CONTENT VARCHAR2(400) NOT NULL ,
    IMAGE_SELL   VARCHAR2(100) NULL    ,
    COUNT        NUMBER        NOT NULL ,
    PRICE        NUMBER        NOT NULL ,
    SELL_STATUS  CHAR(1)       DEFAULT 'Y',
    CREATE_DATE  DATE          DEFAULT SYSDATE ,
    UPDATE_DATE  DATE          DEFAULT SYSDATE ,
    STATUS       CHAR(1)       DEFAULT 'Y',
    HEART_NUM    NUMBER        NULL,
    USER_NO      NUMBER        NOT NULL,
    CATEGORY_NO  NUMBER        NOT NULL,
    CONSTRAINT PK_SELL PRIMARY KEY (SELL_NO),
        CONSTRAINT FK_MEMBER_TO_SELL FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO),
    CONSTRAINT FK_CATEGORY_TO_SELL FOREIGN KEY (CATEGORY_NO) REFERENCES CATEGORY(CATEGORY_NO)
);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (1, 'Title 1', 'Content 1', 'surface1.jpg', 10, 1000, 'Y', SYSDATE, SYSDATE, 'Y', 5, 1, 10);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (2, 'Title 2', 'Content 2', 'surface2.jpg', 5, 2000, 'Y', SYSDATE, SYSDATE, 'Y', 3, 2, 10);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (3, 'Title 3', 'Content 3', 'surface3.jpg', 8, 1500, 'Y', SYSDATE, SYSDATE, 'Y', 7, 3, 10);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (4, 'Title 4', 'Content 4', 'surface4.jpg', 12, 3000, 'Y', SYSDATE, SYSDATE, 'Y', 10, 1, 10);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (5, 'Title 5', 'Content 5', 'surface5.jpg', 20, 2500, 'Y', SYSDATE, SYSDATE, 'Y', 6, 2, 10);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (6, 'Title 6', 'Content 6', 'surface6.jpg', 15, 500, 'Y', SYSDATE, SYSDATE, 'Y', 8, 3, 10);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (7, 'Title 7', 'Content 7', 'apple1.jpg', 9, 1700, 'Y', SYSDATE, SYSDATE, 'Y', 2, 1, 10);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (8, 'Title 8', 'Content 8', 'apple2.jpg', 14, 1100, 'Y', SYSDATE, SYSDATE, 'Y', 9, 2, 10);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (9, 'Title 9', 'Content 9', 'apple3.jpg', 7, 1300, 'Y', SYSDATE, SYSDATE, 'Y', 4, 3, 10);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (10, 'Title 10', 'Content 10', 'apple4.png', 6, 1400, 'Y', SYSDATE, SYSDATE, 'Y', 5, 1, 10);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (11, 'Title 11', 'Content 11', 'apple5.jpg', 11, 2200, 'Y', SYSDATE, SYSDATE, 'Y', 3, 2, 10);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (12, 'Title 12', 'Content 12', 'apple6.jpg', 13, 2800, 'Y', SYSDATE, SYSDATE, 'Y', 7, 3, 10);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (13, 'Title 13', 'Content 13', 'apple7.jpg', 10, 3000, 'Y', SYSDATE, SYSDATE, 'Y', 6, 1, 10);

INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (14, 'Title 14', 'Content 14', 'home1.jpg', 10, 1400, 'Y', SYSDATE, SYSDATE, 'Y', 3, 1, 20);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (15, 'Title 15', 'Content 15', 'home2.jpg', 5, 2000, 'Y', SYSDATE, SYSDATE, 'Y', 6, 2, 20);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (16, 'Title 16', 'Content 16', 'home3.jpg', 8, 1800, 'Y', SYSDATE, SYSDATE, 'Y', 9, 3, 20);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (17, 'Title 17', 'Content 17', 'home4.jpg', 12, 2500, 'Y', SYSDATE, SYSDATE, 'Y', 7, 1, 20);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (18, 'Title 18', 'Content 18', 'home5.jpg', 15, 3200, 'Y', SYSDATE, SYSDATE, 'Y', 4, 2, 20);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (19, 'Title 19', 'Content 19', 'home6.jpg', 7, 2900, 'Y', SYSDATE, SYSDATE, 'Y', 10, 3, 20);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (20, 'Title 20', 'Content 20', 'home7.jpg', 20, 3100, 'Y', SYSDATE, SYSDATE, 'Y', 8, 1, 20);

INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (21, 'Title 21', 'Content 21', 'b1.jpg', 17, 3000, 'Y', SYSDATE, SYSDATE, 'Y', 5, 1, 30);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (22, 'Title 22', 'Content 22', 'b2.jpg', 18, 4000, 'Y', SYSDATE, SYSDATE, 'Y', 5, 3, 30);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (23, 'Title 23', 'Content 23', 'b3.jpg', 20, 5500, 'Y', SYSDATE, SYSDATE, 'Y', 5, 7, 30);

-- CATEGORY_NO 40
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (24, 'Title 24', 'Content 24', 'c1.jpg', 15, 3200, 'Y', SYSDATE, SYSDATE, 'Y', 6, 2, 40);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (25, 'Title 25', 'Content 25', 'c2.jpg', 13, 3400, 'Y', SYSDATE, SYSDATE, 'Y', 7, 3, 40);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (26, 'Title 26', 'Content 26', 'c3.jpg', 18, 3600, 'Y', SYSDATE, SYSDATE, 'Y', 8, 1, 40);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (27, 'Title 27', 'Content 27', 'c4.jpg', 17, 3800, 'Y', SYSDATE, SYSDATE, 'Y', 9, 3, 40);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (28, 'Title 28', 'Content 28', 'c5.jpg', 14, 4000, 'Y', SYSDATE, SYSDATE, 'Y', 5, 7, 40);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (29, 'Title 29', 'Content 29', 'c6.jpg', 20, 4200, 'Y', SYSDATE, SYSDATE, 'Y', 4, 2, 40);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (30, 'Title 30', 'Content 30', 'c7.jpg', 19, 4400, 'Y', SYSDATE, SYSDATE, 'Y', 3, 3, 40);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (31, 'Title 31', 'Content 31', 'c8.jpg', 16, 4600, 'Y', SYSDATE, SYSDATE, 'Y', 2, 1, 40);

-- CATEGORY_NO 50
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (32, 'Title 32', 'Content 32', 'q1.jpg', 15, 3200, 'Y', SYSDATE, SYSDATE, 'Y', 6, 2, 50);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (33, 'Title 33', 'Content 33', 'q2.jpg', 13, 3400, 'Y', SYSDATE, SYSDATE, 'Y', 7, 3, 50);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (34, 'Title 34', 'Content 34', 'q3.jpg', 18, 3600, 'Y', SYSDATE, SYSDATE, 'Y', 8, 1, 50);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (35, 'Title 35', 'Content 35', 'q4.jpg', 17, 3800, 'Y', SYSDATE, SYSDATE, 'Y', 9, 3, 50);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (36, 'Title 36', 'Content 36', 'q5.jpg', 14, 4000, 'Y', SYSDATE, SYSDATE, 'Y', 5, 7, 50);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (37, 'Title 37', 'Content 37', 'q6.jpg', 20, 4200, 'Y', SYSDATE, SYSDATE, 'Y', 4, 2, 50);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (38, 'Title 38', 'Content 38', 'q7.jpg', 19, 4400, 'Y', SYSDATE, SYSDATE, 'Y', 3, 3, 50);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (39, 'Title 39', 'Content 39', 'q8.jpg', 16, 4600, 'Y', SYSDATE, SYSDATE, 'Y', 2, 1, 50);

-- CATEGORY_NO 60
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (40, 'Title 40', 'Content 40', 'p1.jpg', 15, 3200, 'Y', SYSDATE, SYSDATE, 'Y', 6, 2, 60);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (41, 'Title 41', 'Content 41', 'p2.jpg', 13, 3400, 'Y', SYSDATE, SYSDATE, 'Y', 7, 3, 60);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (42, 'Title 42', 'Content 42', 'p3.jpg', 18, 3600, 'Y', SYSDATE, SYSDATE, 'Y', 8, 1, 60);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (43, 'Title 43', 'Content 43', 'p4.png', 17, 3800, 'Y', SYSDATE, SYSDATE, 'Y', 9, 3, 60);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (44, 'Title 44', 'Content 44', 'p5.png', 14, 4000, 'Y', SYSDATE, SYSDATE, 'Y', 5, 7, 60);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (45, 'Title 45', 'Content 45', 'p6.png', 20, 4200, 'Y', SYSDATE, SYSDATE, 'Y', 4, 2, 60);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (46, 'Title 46', 'Content 46', 'p7.png', 19, 4400, 'Y', SYSDATE, SYSDATE, 'Y', 3, 3, 60);
INSERT INTO SELL (SELL_NO, SELL_TITLE, SELL_CONTENT, IMAGE_SELL, COUNT, PRICE, SELL_STATUS, CREATE_DATE, UPDATE_DATE, STATUS, HEART_NUM, USER_NO, CATEGORY_NO) 
VALUES (47, 'Title 47', 'Content 47', 'p8.png', 16, 4600, 'Y', SYSDATE, SYSDATE, 'Y', 2, 1, 60);

select * from sell;
select * from member;
--게시글 첨부파일 --

CREATE TABLE SFILE (
    SFILE_NO     NUMBER        NOT NULL,
    ORIGIN_NAME  VARCHAR2(300) NOT NULL,
    CHANGE_NAME  VARCHAR2(300) NOT NULL,
    UPLOAG_DATE  DATE          NOT NULL,
    FILE_PATH    VARCHAR2(1000) NULL,
    FILE_TYPE    VARCHAR2(1)   NOT NULL,
    STATUS       VARCHAR2(1)   DEFAULT 'Y',
    SELL_NO      NUMBER        NOT NULL ,
    CONSTRAINT PK_SFILE PRIMARY KEY (SFILE_NO),
    CONSTRAINT FK_SELL_TO_SFILE FOREIGN KEY (SELL_NO) REFERENCES SELL(SELL_NO)   
);


--구매 내역 --

CREATE TABLE PURCHASE (
    PUB_NO        NUMBER        NOT NULL,
    CREATE_DATE   DATE         	DEFAULT SYSDATE,
    PRICE         NUMBER        NULL,
    ORDER_NO      VARCHAR2(200) NULL,
    DEPO_STATUS   CHAR(1)       DEFAULT 'Y' ,
    SELL_NO       NUMBER        NOT NULL,
    USER_NO       NUMBER        NOT NULL,
    CONSTRAINT PK_PURCHASE PRIMARY KEY (PUB_NO),
    CONSTRAINT FK_SELL_TO_PURCHASE FOREIGN KEY (SELL_NO) REFERENCES SELL(SELL_NO),
  	CONSTRAINT FK_MEMBER_TO_PURCHASE FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO) 
);

select * from member where user_id='k1';
select 'k'||user_no from member;
updtae member m1 set user_id = (select 'k'||user_no from member M2) WHERE M1.USER_NO=M2.USER_NO; 
-- 리뷰 --

CREATE TABLE REVIEW (
    REV_NO       NUMBER        NOT NULL ,
    REV_CONTENT  VARCHAR2(100) NOT NULL,
    REV_SCORE    NUMBER        NOT NULL ,
    CREATE_DATE  DATE          DEFAULT SYSDATE,
    STATUS       CHAR(1)       DEFAULT 'Y' ,
    SELL_NO     NUMBER        NOT NULL ,
    USER_NO     NUMBER        NOT NULL ,
    CONSTRAINT PK_REVIEW PRIMARY KEY (REV_NO),
    CONSTRAINT FK_SELL_TO_REVIEW FOREIGN KEY (SELL_NO) REFERENCES SELL(SELL_NO),
    CONSTRAINT FK_MEMBER_TO_REVIEW FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO)
);


--팔로우 --
drop table FOLLOW cascade constraints;
CREATE TABLE FOLLOW (
    FL_ID        NUMBER NOT NULL,
    CREATE_DATE  DATE   DEFAULT SYSDATE,
    FW_ID        NUMBER NOT NULL,
    CONSTRAINT FK_MEMBER_TO_FOLLOW_1 FOREIGN KEY (FL_ID) REFERENCES MEMBER(USER_NO),
    CONSTRAINT FK_MEMBER_TO_FOLLOWING FOREIGN KEY (FW_ID) REFERENCES MEMBER(USER_NO)
    
);

drop table HEART cascade constraints;
--CREATE_HARTE = CREATE_DATE 로 변경 확인--
--찜 --

CREATE TABLE HEART (
    SELL_NO      NUMBER NOT NULL ,
    USER_NO      NUMBER NOT NULL ,
    CREATE_DATE DATE DEFAULT SYSDATE ,
    HEART_NO     NUMBER NULL ,
    CONSTRAINT PK_HEART PRIMARY KEY (SELL_NO, USER_NO),
    CONSTRAINT FK_SELL_TO_HEART FOREIGN KEY (SELL_NO) REFERENCES SELL(SELL_NO),
    CONSTRAINT FK_MEMBER_TO_HEART FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO)
);


--최근 본 상품 -- 
drop table RECENT cascade constraints;
--CREATE_DATE -- 오타 수정했음 
CREATE TABLE RECENT (
    RECENT_NO   NUMBER NOT NULL ,
    CREATE_DATE  DATE     DEFAULT SYSDATE,
    STATUS      CHAR(1)   DEFAULT 'Y',
    USER_NO    NUMBER  NOT NULL,
    SELL_NO     NUMBER  NOT NULL,
    CONSTRAINT PK_RECENT PRIMARY KEY (RECENT_NO),
    CONSTRAINT FK_MEMBER_TO_RECENT FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO),
    CONSTRAINT FK_SELL_TO_RECENT FOREIGN KEY (SELL_NO) REFERENCES SELL(SELL_NO)
);


--계좌 번호 --

CREATE TABLE ACCOUNT (
    ACCOUNT_ID   NUMBER NOT NULL ,
    ACCOUNT      NUMBER NOT NULL ,
    BANK         VARCHAR2(40) NULL ,
    USER_NO      NUMBER NOT NULL ,
    CONSTRAINT PK_ACCOUNT PRIMARY KEY (ACCOUNT_ID),
    CONSTRAINT FK_MEMBER_TO_ACCOUNT FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO)
);



-- 차단 -- 
CREATE TABLE BLOCK (
    BLOCK_NUM    NUMBER NOT NULL COMMENT '차단 목록 고유번호',
    BLOCKER_NO   NUMBER NOT NULL COMMENT '회원 고유 식별번호',
    BLOCKED_NO   NUMBER NOT NULL COMMENT '회원 고유 식별번호',
    CONSTRAINT PK_BLOCK PRIMARY KEY (BLOCK_NUM),
    CONSTRAINT FK_MEMBER_TO_BLOCKERNUM FOREIGN KEY (BLOCK_NUM) REFERENCES MEMBER(USER_NO),
    
);


--채팅방 -- 
CREATE TABLE CHAT_ROOM (
    CHATROOM_NO NUMBER NOT NULL ,
    CREATE_DATE DATE  DEFAULT SYSDATE ,
    STATUS      CHAR(1)  DEFAULT 'Y' ,
    SELL_NO     NUMBER  NOT NULL ,
    USER_NO     NUMBER  NOT NULL ,
    CONSTRAINT PK_CHAT_ROOM PRIMARY KEY (CHATROOM_NO),
    CONSTRAINT FK_MEMBER_TO_CHAT_ROOM FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO),
    CONSTRAINT FK_SELL_TO_CHAT_ROOM FOREIGN KEY (SELL_NO) REFERENCES SELL(SELL_NO)
);

--채팅 메세지 --

CREATE TABLE CHAT_MESSEGE (
    MESSEGE_NO       NUMBER        NOT NULL  ,
    MESSAGE_CONTENT  VARCHAR2(4000) NOT NULL ,
    CREATE_DATE      DATE           DEFAULT SYSDATE ,
    READ_STATUS      CHAR(1)        DEFAULT 'M' ,
    CHATROOM_NO     NUMBER        NOT NULL ,
    USER_NO         NUMBER        NOT NULL,
    CONSTRAINT PK_CHAT_MESSEGE PRIMARY KEY (MESSEGE_NO),
    CONSTRAINT FK_MEMBER_TO_CHAT_MESSEGE FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO),
    CONSTRAINT FK_CAHT_ROOM_TO_GHAT_MESSEGE FOREIGN KEY (CHATROOM_NO) REFERENCES CHAT_ROOM(CHATROOM_NO)
);


--채팅방 JOIN --

CREATE TABLE CHAT_ROOM_JOIN (
    CHATROOM_NO NUMBER NOT NULL ,
    USER_NO     NUMBER NOT NULL ,
    CONSTRAINT PK_CHAT_ROOM_JOIN PRIMARY KEY (CHATROOM_NO, USER_NO),
    CONSTRAINT FK_CHAT_ROOM_TO_CHAT_ROOM_JOIN FOREIGN KEY (CHATROOM_NO) REFERENCES CHAT_ROOM(CHATROOM_NO),
    CONSTRAINT FK_MEMBER_TO_CHAT_ROOM_JOIN FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO)
);

--채팅방 첨부파일 테이블 -- 

CREATE TABLE CFILE (
    CFILE_NO      NUMBER        NOT NULL,
    CFILE_NAME    VARCHAR2(200) NOT NULL,
    CHANEGE_NAME  VARCHAR2(300) NOT NULL,
    CREATE_DATE   DATE              DEFAULT SYSDATE,
    FILE_PATH     VARCHAR2(500) NULL    ,
    STATUS        CHAR(1)       DEFAULT 'Y' ,
    USER_NO       NUMBER        NOT NULL ,
    CHATROOM_NO  NUMBER        NOT NULL ,
    CONSTRAINT PK_CFILE PRIMARY KEY (CFILE_NO),
    CONSTRAINT FK_MEMBER_TO_CFILE FOREIGN KEY (USER_NO) REFERENCES MEMBER(USER_NO),
    CONSTRAINT FK_CHAT_ROOM_TO_CFILE FOREIGN KEY (CHATROOM_NO) REFERENCES CHAT_ROOM(CHATROOM_NO)
    
);

-- 신고 하기 
CREATE TABLE REPORT (
    REPORT_NO      NUMBER        NOT NULL ,
    REPORT_CONTENT  VARCHAR2(4000) NOT NULL,
    CREATE_DATE    DATE          DEFAULT SYSDATE ,
    STATUS         CHAR(1)         DEFAULT 'Y' ,
    REPORTER_NO    NUMBER        NOT NULL ,
    REPORTED_NO    NUMBER        NOT NULL ,
    CONSTRAINT PK_REPORT PRIMARY KEY (REPORT_NO),
    CONSTRAINT FK_MEMBER_TO_REPORTER FOREIGN KEY (REPORTER_NO) REFERENCES MEMBER(USER_NO),
    CONSTRAINT FK_MEMBER_TO_REPORTED_1 FOREIGN KEY (REPORTED_NO) REFERENCES MEMBER(USER_NO)
    
);
drop table REPORT cascade constraints;

select * from member where BLACKLIST='Y';